# Disable sudo to speed up the build
sudo: false

branches:
  only: 
    - master
language: python
python: 
  - "3.6" 
# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt

